features_width: 43
features_len_max: 8096
tokens_len_max: 750
vocab_size: 64
attention_params {
  type: "window"
  s_min: 0
  s_max: 50
  v_min: 1.2
  v_max: 2.0
}
encoder_layer: "1"
encoder_layer: "2"
encoder_layer: "2"
encoder_layer: "2"
