features_width: 40
features_len_max: 4096
tokens_len_max: 500
vocab_size: 64
attention_params {
  type: "window"
  s_min: 0
  s_max: 50
  v_min: 0.7
  v_max: 1.5
}
encoder_layer: "1"
encoder_layer: "2"
encoder_layer: "2"
encoder_layer: "2"
