features_width: 43
features_len_max: 4256
tokens_len_max: 256
attention_params {
  type: "window"
  s_min: 0
  s_max: 40
  v_min: 1.0
  v_max: 2.0
}
encoder_layer: 1
encoder_layer: 2
encoder_layer: 2
encoder_layer: 2
